# Generated by Django 5.0.4 on 2024-05-07 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_perf', '0001_initial'),
        ('vendor_pfp', '0003_alter_vendor_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='average_response_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='fulfillment_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='on_time_delivery_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='quality_rating_avg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor_pfp.vendor_profile'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
