# Generated by Django 5.0.4 on 2024-05-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_pfp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_profile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vendor_profile',
            name='average_response_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vendor_profile',
            name='contact_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vendor_profile',
            name='fulfillment_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vendor_profile',
            name='name',
            field=models.CharField(default='New vendor', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor_profile',
            name='on_time_delivery_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vendor_profile',
            name='quality_rating_avg',
            field=models.FloatField(null=True),
        ),
    ]
