# Generated by Django 5.0.4 on 2024-05-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_pfp', '0002_vendor_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_profile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
