# Generated by Django 5.0.4 on 2024-05-07 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_pfp', '0003_alter_vendor_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_profile',
            name='vendor_code',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
