# Generated by Django 5.0.4 on 2024-05-07 12:37

import uuid
from django.db import migrations

def gen_uuid(apps, schema_editor):
    Vendor_Profile = apps.get_model("vendor_pfp", "Vendor_Profile")
    for row in Vendor_Profile.objects.all():
        row.vendor_code = uuid.uuid4()
        row.save(update_fields=["vendor_code"])

class Migration(migrations.Migration):

    dependencies = [
        ('vendor_pfp', '0004_vendor_profile_vendor_code'),
    ]

    operations = [
         # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
