# Generated by Django 5.0.4 on 2024-05-07 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_pfp', '0005_auto_20240507_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_profile',
            name='vendor_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
