# Generated by Django 5.0.4 on 2024-05-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_track', '0002_po_model_acknowledgment_date_po_model_delivery_date_and_more'),
    ]

    operations = [
    ]
