# Generated by Django 5.0.4 on 2024-05-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_track', '0003_auto_20240507_1715'),
    ]

    operations = [
    ]
