# Generated by Django 5.0.4 on 2024-05-07 12:14

import uuid
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('order_track', '0007_auto_20240507_1744'),
    ]

    operations = [
         migrations.AlterField(
            model_name='po_model',
            name='po_number',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
